---

default: true
header-style:
  style: atx
no-trailing-spaces:
  br_spaces: 2
line-length: false
no-duplicate-header:
  siblings_only: true
hr-style:
  style: "---"
code-block-style:
  style: fenced
code-fence-style:
  style: backtick
