---

name: Markdownlint

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    branches:
      - main

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Markdown Lint
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: "."
          config_file: ".markdownlint.yml"
